#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet --no-tray-icon &
fi

# Volume control applet
if [ -z "$(pgrep volti)" ] ; then
    volti &
fi

# Clipboard manager
if [ -z "$(pgrep parcellite)" ] ; then
    parcellite &
fi

# Dropbox
if [ -x "/home/akshay/.dropbox-dist/dropboxd" ] ; then
    /home/akshay/.dropbox-dist/dropboxd &
fi

# Screensaver
if [ -z "$(pgrep gnome-screensaver)" ] ; then
    gnome-screensaver &
fi

# On login, we unlock the ssh keychain so we're not prompted for 
# passphrases later. We pipe /dev/null to ssh-add to make it realize 
# it's not running in a terminal. Otherwise, it won't launch the prompt.

export SSH_ASKPASS="/usr/bin/ssh-askpass"
cat /dev/null | ssh-add &
