#!/bin/bash
# 
# xmonad startup script. Intended to be run from an xsession configuration
# to run xmonad and some associated programs.

# Load X resources (fixes some font issues)
xrdb -merge .Xresources

# Load custom keymap
xmodmap ~/.xmodmaprc

# Background
feh --no-fehbg --bg-tile ~/.xmonad/images/linen.png

# Status tray
stalonetray \
  --icon-gravity E \
  --geometry 5x1-0+0 \
  --max-geometry 5x1-0+0 \
  --background '#000000' \
  --skip-taskbar \
  --icon-size 21 \
  --kludges force_icons_size \
  --window-strut none \
&

# Gnome apps expect the keyring
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

exec xmonad
