#!/bin/bash
# 
# xmonad startup script. Intended to be run from an xsession configuration
# to run xmonad and some associated programs.

# Load X resources (fixes some font issues)
xrdb -merge .Xresources

# Load custom keymap
#xmodmap ~/.xmodmaprc

# Background
feh --no-fehbg --bg-tile ~/.xmonad/images/linen.png

# Status tray
trayer --edge top --align right --SetDockType true --expand true --width 10 --transparent true --alpha 0 --tint 0x000000 --height 21 &

# Gnome apps expect the keyring
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

exec xmonad
